AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation EC2 Instance template for onboarding new client.
Parameters:
  ClientName:
    Description: Client Name
    Type: 'String'
  TimeZone:
    Description: Time Zone of client
    Type: String
    Default: Eastern Standard Time
    AllowedValues:
      - Pacific Standard Time
      - Mountain Standard Time
      - Central Standard Time
      - Eastern Standard Time
      - Atlantic Standard Time
    ConstraintDescription: must be a valid EC2 instance type.
Resources:
  myssmdocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: (Required) The ID of the AWS Directory Service directory.
            default: 'd-9a671b1647'
          directoryName:
            type: String
            description: >-
              (Required) The name of the directory; for example,
              test.example.com
            default: 'example.cloud'
          dnsIpAddresses:
            type: StringList
            default: [172.31.17.209,172.31.45.237]
            description: >-
              (Optional) The IP addresses of the DNS servers in the directory.
              Required when DHCP is not configured. Learn more at
              http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_get_dns_addresses.html
            allowedPattern: >-
              ((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
        runtimeConfig:
          'aws:domainJoin':
            properties:
              directoryId: '{{ directoryId }}'
              directoryName: '{{ directoryName }}'
              dnsIpAddresses: '{{ dnsIpAddresses }}'
  Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      IamInstanceProfile: SurePoint-EC2-Instance-Profile
      SsmAssociations:
        - DocumentName: !Ref myssmdocument
          AssociationParameters:
            - Key: directoryId
              Value:
                - d-9a671b1647
            - Key: directoryName
              Value:
                - example.cloud
            - Key: dnsIpAddresses
              Value:
                - 172.31.17.209
                - 172.31.45.237
      InstanceType: t2.medium
      KeyName: Testing-SurePoint-Keypair
      ImageId: ami-017ab573701202ba1
      SecurityGroupIds: [sg-055c50c6eda5b13c5]
      # DisableApiTermination set to True before deployment on live
      DisableApiTermination: false
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              <script>
            
            - 'tzutil /s "'
            - !Ref 'TimeZone'
            - '" '
            
            - |+

            - |
              </script>
            - |
              <powershell>
            - >
              $LocalTempDir = $env:TEMP; $ChromeInstaller = "ChromeInstaller.exe"; (new-object    System.Net.WebClient).DownloadFile('http://dl.google.com/chrome/install/375.126/chrome_installer.exe', "$LocalTempDir\$ChromeInstaller"); & "$LocalTempDir\$ChromeInstaller" /silent /install; $Process2Monitor =  "ChromeInstaller"; Do { $ProcessesFound = Get-Process | ?{$Process2Monitor -contains $_.Name} | Select-Object -ExpandProperty Name; If ($ProcessesFound) { "Still running: $($ProcessesFound -join ', ')" | Write-Host; Start-Sleep -Seconds 2 } else { rm "$LocalTempDir\$ChromeInstaller" -ErrorAction SilentlyContinue -Verbose } } Until (!$ProcessesFound) 
            - |
              $LocalTempDir = $env:TEMP; $NotepadInstaller = "npp.8.4.6.Installer.x64.exe"; (new-object    System.Net.WebClient).DownloadFile('https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.6/npp.8.4.6.Installer.x64.exe', "$LocalTempDir\$NotepadInstaller"); & "$LocalTempDir\$NotepadInstaller" /S; $Process2Monitor =  "NotepadInstaller"; Do { $ProcessesFound = Get-Process | ?{$Process2Monitor -contains $_.Name} | Select-Object -ExpandProperty Name; If ($ProcessesFound) { "Still running: $($ProcessesFound -join ', ')" | Write-Host; Start-Sleep -Seconds 2 } else { rm "$LocalTempDir\$NotepadInstaller" -ErrorAction SilentlyContinue -Verbose } } Until (!$ProcessesFound)
            - >
              $LocalTempDir = $env:TEMP; $7ZipInstaller = "7z2201.exe"; (new-object    System.Net.WebClient).DownloadFile('https://www.7-zip.org/a/7z2201.exe', "$LocalTempDir\$7ZipInstaller"); & "$LocalTempDir\$7ZipInstaller" /S; $Process2Monitor =  "7ZipInstaller"; Do { $ProcessesFound = Get-Process | ?{$Process2Monitor -contains $_.Name} | Select-Object -ExpandProperty Name; If ($ProcessesFound) { "Still running: $($ProcessesFound -join ', ')" | Write-Host; Start-Sleep -Seconds 2 } else { rm "$LocalTempDir\$7ZipInstaller" -ErrorAction SilentlyContinue -Verbose } } Until (!$ProcessesFound)
            
            - |+

            - |
            - </powershell>
      Tags:
        - Key: Name
          Value: !Ref ClientName
        - Key: Client
          Value: surepoint
